# Generated by Django 2.1.15 on 2020-05-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='do_you_like_potato',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
