# Generated by Django 2.1.15 on 2020-05-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_do_you_like_potato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='do_you_like_potato',
        ),
    ]
